# Generated by Django 3.2.4 on 2021-06-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_companynews_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='api.company'),
            preserve_default=False,
        ),
    ]
